const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const COLS=24,ROWS=18,CELL=10;const screens={home:document.getElementById('homeScreen'),game:document.getElementById('gameScreen'),over:document.getElementById('gameOverScreen')};
let snake,food,dir,nextDir,score,highScore=Number(localStorage.getItem('snake3310HighScore')||0),timer,running=false,paused=false,level=1;
const dirs={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
const $=id=>document.getElementById(id);function pad(n){return String(n).padStart(4,'0')}
function show(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
function updateScores(){$('score').textContent=pad(score);$('highScore').textContent=pad(highScore);$('homeHighScore').textContent=pad(highScore);$('level').textContent=String(level).padStart(2,'0')}
function randomFood(){let f;do{f={x:Math.floor(Math.random()*COLS),y:Math.floor(Math.random()*ROWS)}}while(snake.some(s=>s.x===f.x&&s.y===f.y));return f}
function startGame(){clearInterval(timer);snake=[{x:Math.floor(COLS/2),y:Math.floor(ROWS/2)},{x:Math.floor(COLS/2)-1,y:Math.floor(ROWS/2)},{x:Math.floor(COLS/2)-2,y:Math.floor(ROWS/2)}];dir=dirs.right;nextDir=dir;score=0;level=1;paused=false;running=true;food=randomFood();$('pauseLabel').classList.add('hidden');updateScores();show('game');draw();timer=setInterval(step,230)}
function keepNuiFocus(){try{window.focus();document.body.focus()}catch(e){}}
function setDirection(name){if(!running||paused)return;const d=dirs[name];if(d.x===-dir.x&&d.y===-dir.y)return;nextDir=d;beep(520,25);keepNuiFocus()}
function pointDirection(event){if(!running||paused)return;event.preventDefault();const rect=canvas.getBoundingClientRect(),scaleX=canvas.width/rect.width,scaleY=canvas.height/rect.height;const px=(event.clientX-rect.left)*scaleX,py=(event.clientY-rect.top)*scaleY,headX=(snake[0].x+.5)*CELL,headY=(snake[0].y+.5)*CELL,dx=px-headX,dy=py-headY;if(Math.abs(dx)>Math.abs(dy))setDirection(dx>0?'right':'left');else if(dy!==0)setDirection(dy>0?'down':'up')}
function step(){if(!running||paused)return;dir=nextDir;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>=COLS||head.y<0||head.y>=ROWS||snake.some(s=>s.x===head.x&&s.y===head.y)){endGame();return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=10;level=Math.min(9,1+Math.floor(score/50));if(score>highScore){highScore=score;localStorage.setItem('snake3310HighScore',highScore)}food=randomFood();beep(880,70);clearInterval(timer);timer=setInterval(step,Math.max(65,150-(level-1)*10))}else snake.pop();updateScores();draw()}
function draw(){ctx.fillStyle='#9bbc0f';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#76920d';ctx.lineWidth=1;for(let x=0;x<=canvas.width;x+=CELL){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<=canvas.height;y+=CELL){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}ctx.fillStyle='#0f380f';ctx.fillRect(food.x*CELL+1,food.y*CELL+1,CELL-2,CELL-2);snake.forEach((s,i)=>{ctx.fillStyle='#0f380f';ctx.fillRect(s.x*CELL+1,s.y*CELL+1,CELL-2,CELL-2);if(i===0){ctx.fillStyle='#9bbc0f';ctx.fillRect(s.x*CELL+3,s.y*CELL+3,2,2)}})}
function endGame(){running=false;clearInterval(timer);beep(160,180);$('finalScore').textContent=pad(score);$('finalHighScore').textContent=pad(highScore);show('over')}
function togglePause(){if(!running)return;paused=!paused;$('pauseLabel').classList.toggle('hidden',!paused);if(!paused)draw();beep(300,30)}
let audio;function beep(freq,duration){try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='square';g.gain.value=.025;o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration/1000)}catch(e){}}
$('startButton').onclick=startGame;$('retryButton').onclick=startGame;$('menuButton').onclick=()=>{running=false;clearInterval(timer);show('home');updateScores()};
document.getElementById('gameScreen').addEventListener('pointerdown',pointDirection,{passive:false});
document.querySelectorAll('button').forEach(button=>button.addEventListener('pointerup',()=>{button.blur();keepNuiFocus()}));document.addEventListener('pointerdown',keepNuiFocus);keepNuiFocus();updateScores();show('home');
