// Snake Multiplayer — salas públicas via WebSocket
const WebSocket=require('ws');const http=require('http');
const PORT=process.env.PORT||3000,MAX_PLAYERS=10,MIN_PLAYERS=5,WORLD=3000,SPAWN_INVULN_MS=3000;
const colors=['#4ade80','#60a5fa','#f472b6','#facc15','#c084fc','#fb7185','#22d3ee','#fb923c','#a3e635','#e879f9'];
const rooms=new Map();let botSeq=0;
function cleanName(v,fallback){return String(v||fallback).trim().slice(0,24)||fallback}
function slug(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function spawn(){return{x:100+Math.random()*(WORLD-200),y:100+Math.random()*(WORLD-200)}}
function bodyAt(p){return Array.from({length:18},(_,i)=>({x:p.x-i*18,y:p.y}))}
function makeRoom(name){let id=slug();while(rooms.has(id))id=slug();const room={id,name:cleanName(name,'Sala '+id),players:new Map(),foods:Array.from({length:180},()=>({x:40+Math.random()*(WORLD-80),y:40+Math.random()*(WORLD-80),r:5,value:10}))};rooms.set(id,room);return room}
function makeBot(index,room){const p=spawn();return{id:'bot-'+room.id+'-'+index,name:'Bot '+index,color:colors[index%colors.length],score:0,alive:true,body:bodyAt(p),dir:{x:Math.random()<.5?1:-1,y:0},aiTimer:0,target:null,isBot:true,ws:null,invulnerableUntil:Date.now()+SPAWN_INVULN_MS}}
function humans(room){return [...room.players.values()].filter(p=>!p.isBot)}
function addBots(room){while(room.players.size<MIN_PLAYERS&&room.players.size<MAX_PLAYERS){const b=makeBot(++botSeq,room);room.players.set(b.id,b)}}
function removeExtraBots(room){while(room.players.size>MIN_PLAYERS){const bot=[...room.players.values()].find(p=>p.isBot);if(!bot)break;room.players.delete(bot.id)}}
function dropFood(room,p){const h=p.body[0],count=Math.min(80,Math.max(12,Math.floor(p.body.length/2)));for(let i=0;i<count;i++)room.foods.push({x:Math.max(25,Math.min(WORLD-25,h.x+(Math.random()-.5)*220)),y:Math.max(25,Math.min(WORLD-25,h.y+(Math.random()-.5)*220)),r:5,value:20})}
function randomTurn(p){p.dir=p.dir.x!==0?(Math.random()<.5?{x:0,y:1}:{x:0,y:-1}):(Math.random()<.5?{x:1,y:0}:{x:-1,y:0})}
function steer(p,f){const h=p.body[0],dx=f.x-h.x,dy=f.y-h.y;if(Math.abs(dx)>Math.abs(dy)){if(dx>0&&p.dir.x>=0)p.dir={x:1,y:0};else if(dx<0&&p.dir.x<=0)p.dir={x:-1,y:0}}else{if(dy>0&&p.dir.y>=0)p.dir={x:0,y:1};else if(dy<0&&p.dir.y<=0)p.dir={x:0,y:-1}}}
function updateBot(room,p,dt){const h=p.body[0];p.aiTimer-=dt;if(p.aiTimer<=0){p.aiTimer=1+Math.random()*2;let best=null,bd=Infinity;for(const f of room.foods){const d=Math.hypot(f.x-h.x,f.y-h.y);if(d<bd&&d<700){best=f;bd=d}}p.target=best;if(!best||Math.random()<.35)randomTurn(p)}const m=180;if(h.x<m&&p.dir.x<0)p.dir={x:1,y:0};else if(h.x>WORLD-m&&p.dir.x>0)p.dir={x:-1,y:0};else if(h.y<m&&p.dir.y<0)p.dir={x:0,y:1};else if(h.y>WORLD-m&&p.dir.y>0)p.dir={x:0,y:-1};else if(p.target&&Math.random()<.1)steer(p,p.target);const speed=105+Math.min(p.score/40,45),nh={x:h.x+p.dir.x*speed*dt,y:h.y+p.dir.y*speed*dt};if(nh.x<20||nh.y<20||nh.x>WORLD-20||nh.y>WORLD-20){p.alive=false;dropFood(room,p);return}p.body.unshift(nh);let ate=false;for(let i=room.foods.length-1;i>=0;i--)if(Math.hypot(room.foods[i].x-nh.x,room.foods[i].y-nh.y)<20){p.score+=room.foods[i].value;room.foods.splice(i,1);room.foods.push({x:40+Math.random()*(WORLD-80),y:40+Math.random()*(WORLD-80),r:5,value:10});ate=true;break}if(!ate)p.body.pop()}
function state(room){return{type:'state',room:{id:room.id,name:room.name,count:humans(room).length},players:[...room.players.values()].map(p=>({id:p.id,name:p.name,color:p.color,score:p.score,alive:p.alive,body:p.body,dir:p.dir,invulnerableUntil:p.invulnerableUntil})),foods:room.foods}}
function broadcast(room){addBots(room);const s=state(room),data=JSON.stringify(s);for(const c of wss.clients)if(c.readyState===WebSocket.OPEN&&c.roomId===room.id)c.send(JSON.stringify({...s,id:c.playerId}))}
function listRooms(){return [...rooms.values()].map(r=>({id:r.id,name:r.name,count:humans(r).length,max:MAX_PLAYERS})).filter(r=>r.count<MAX_PLAYERS)}
const httpServer=http.createServer((req,res)=>{const path=(req.url||'').split('?')[0];res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Content-Type','application/json');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}if(path==='/status'){const online=[...rooms.values()].reduce((n,r)=>n+humans(r).length,0);res.end(JSON.stringify({online,max:MAX_PLAYERS}));return}if(path==='/rooms'&&req.method==='GET'){res.end(JSON.stringify({rooms:listRooms()}));return}if(path==='/rooms'&&req.method==='POST'){let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{let data={};try{data=JSON.parse(body)}catch{}const room=makeRoom(data.name);res.end(JSON.stringify({room:{id:room.id,name:room.name,count:0,max:MAX_PLAYERS}}))});return}res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'});res.end('Snake Multiplayer server ativo. Use WebSocket ou /rooms.');});
const wss=new WebSocket.Server({server:httpServer});
wss.on('connection',ws=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='rooms'){ws.send(JSON.stringify({type:'rooms',rooms:listRooms()}));return}if(m.type==='createRoom'){const room=makeRoom(m.name);ws.send(JSON.stringify({type:'roomCreated',room:{id:room.id,name:room.name,count:0,max:MAX_PLAYERS}}));return}if(m.type==='join'){const room=rooms.get(String(m.roomId));if(!room){ws.send(JSON.stringify({type:'roomNotFound'}));return}if(humans(room).length>=MAX_PLAYERS){ws.send(JSON.stringify({type:'full'}));return}const bot=[...room.players.values()].find(p=>p.isBot);if(bot)room.players.delete(bot.id);const id=Math.random().toString(36).slice(2),p=spawn();room.players.set(id,{id,name:cleanName(m.name,'Jogador').slice(0,16),color:colors[room.players.size%colors.length],score:0,alive:true,body:bodyAt(p),dir:{x:1,y:0},isBot:false,ws,invulnerableUntil:Date.now()+SPAWN_INVULN_MS});ws.playerId=id;ws.roomId=room.id;addBots(room);broadcast(room)}if(m.type==='direction'&&ws.playerId){const room=rooms.get(ws.roomId),p=room&&room.players.get(ws.playerId);if(p&&p.alive&&Math.abs(m.x)+Math.abs(m.y)===1&&!(m.x===-p.dir.x&&m.y===-p.dir.y))p.dir={x:m.x,y:m.y}}});ws.on('close',()=>{const room=rooms.get(ws.roomId);if(!room)return;if(ws.playerId)room.players.delete(ws.playerId);removeExtraBots(room);if(humans(room).length===0){rooms.delete(room.id)}else{addBots(room);broadcast(room)}})});
function tick(room){addBots(room);for(const p of room.players.values())if(p.alive){if(p.isBot)updateBot(room,p,.1);else{const h=p.body[0],nh={x:h.x+p.dir.x*14.5,y:h.y+p.dir.y*14.5};if(nh.x<20||nh.y<20||nh.x>WORLD-20||nh.y>WORLD-20){p.alive=false;dropFood(room,p);continue}p.body.unshift(nh);let ate=false;for(let i=room.foods.length-1;i>=0;i--)if(Math.hypot(room.foods[i].x-nh.x,room.foods[i].y-nh.y)<20){p.score+=room.foods[i].value;room.foods.splice(i,1);room.foods.push({x:40+Math.random()*(WORLD-80),y:40+Math.random()*(WORLD-80),r:5,value:10});ate=true;break}if(!ate)p.body.pop()}}const alive=[...room.players.values()].filter(p=>p.alive);for(const p of alive){if(Date.now()<(p.invulnerableUntil||0))continue;const h=p.body[0];for(const q of alive)if(p!==q&&Date.now()>=(q.invulnerableUntil||0)){if(Math.hypot(h.x-q.body[0].x,h.y-q.body[0].y)<18){p.alive=false;q.alive=false;dropFood(room,p);dropFood(room,q);break}for(let i=5;i<q.body.length;i++)if(Math.hypot(h.x-q.body[i].x,h.y-q.body[i].y)<15){p.alive=false;dropFood(room,p);break}if(!p.alive)break}}for(const [id,p] of room.players)if(!p.alive&&p.isBot)room.players.delete(id);if(humans(room).length)broadcast(room)}
setInterval(()=>{for(const room of rooms.values())tick(room)},100);setInterval(()=>{for(const room of rooms.values())if(humans(room).length)broadcast(room)},5000);httpServer.listen(PORT,()=>console.log(`Snake server running on port ${PORT}`));
